database: mysql

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    initialization-mode: always
    url: jdbc:mysql://${DATASOURCE_HOST}:3306/dashboard?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}
  mvc:
    view:
      prefix: /view/
      suffix: .jsp
    static-path-pattern: /assets/**

  resources:
    static-locations: /assets/

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GIT_CLIENT_ID}
            clientSecret: ${GIT_CLIENT_SECRET}

