version: '2'
services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  database:
    image: mysql:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 143179179
      MYSQL_DATABASE: logiweb
      MYSQL_PASSWORD: 143179179

  config-service:
    image: tuanalexeu/config-service:final-task
    ports:
      - "8888:8888"

  auth-service:
    image: tuanalexeu/auth-service:final-task
    ports:
      - "8088:8088"
    depends_on:
      - database
      - config-service
    environment:
      PROFILE: "default"
      SERVER_PORT: "8088"
      CONFIGSERVER_URI: "https://config-service:8888"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "3306"

  logiweb-service:
    image: tuanalexeu/logiweb-service:final-task
    ports:
      - "8080:8080"
    depends_on:
      - database
      - config-service
      - rabbitmq
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "https://config-service:8888"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "3306"

#networks:
#  rabbitmq_go_net:
#    driver: bridge