version: '2'
services:

#  eurekaserver:
#    image: tuanalexeu/eureka-service:final-task
#    mem_limit: 1073741824
#    ports:
#      - "8761:8761"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  config-service:
    image: tuanalexeu/config-service:final-task
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY: "IMSYMMETRIC"

  database:
    image: mysql:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 143179179
      MYSQL_DATABASE: logiweb
      MYSQL_PASSWORD: 143179179

#  auth-service:
#    image: tuanalexeu/auth-service:final-task
#    ports:
#      - "8080:8080"
#    depends_on:
#      - database
#      - config-service
#    environment:
#      PROFILE: "default"
#      CONFIGSERVER_URI: "http://config-service:8888"
#      CONFIGSERVER_PORT: "8888"
#      DATABASESERVER_PORT: "3306"
#      ENCRYPT_KEY: "IMSYMMETRIC"

  logiweb-service:
    image: tuanalexeu/logiweb-service:final-task
    ports:
      - "8080:8080"
    depends_on:
      - database
      - config-service
      - rabbitmq
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://config-service:8888"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "3306"
      ENCRYPT_KEY: "IMSYMMETRIC"

networks:
  rabbitmq_go_net:
    driver: bridge