apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-service
  labels:
    app: dashboard-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-service
  template:
    metadata:
      labels:
        app: dashboard-service
    spec:
      containers:
        - name: dashboard-service
          image: tuanalexeu/dashboard-service:final-task
          ports:
            - containerPort: 8088