database: mysql

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    initialization-mode: always
    url: jdbc:mysql://${DATASOURCE_HOST}:3306/logiweb?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}

  mvc:
    view:
      prefix: /view/
      suffix: .jsp
    static-path-pattern: /assets/**

  resources:
    static-locations: /assets/