apiVersion: final-task/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mysql:8.0.23
          ports:
            - containerPort: 3306