server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: ${GIT_CONFIG_URI}
          searchPaths: chat-service,eureka-service,logiweb-service,client-order-service
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}

# enable all actuator endpoints for testing (review this for real deployments)
management.endpoints.web:
  include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://34.88.16.195/eureka/