server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/tuanalexeu/config-repo
          searchPaths: auth-service,logiweb-service
          username: tuanalexeu
          password: 143179179AAa