server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_URI}
          searchPaths: auth-service,logiweb-service,eureka-service

# enable all actuator endpoints for testing (review this for real deployments)
management.endpoints.web:
  include: '*'